---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by CHH.
--- DateTime: 2021/1/22 16:55redis.call('LLEN', KEYS[1]);
---
--- ARGV[1] 系统当前时间  ARGV[2] --每多少毫秒放入一个令牌  ARGV[3] 令牌桶容量  ARGV[4] 一次性取出令牌数量
local a = redis.call('LLEN', KEYS[1]);
local b = redis.call('LINDEX', KEYS[1], tonumber(a) - 1);
local c = (tonumber(ARGV[1]) - tonumber(b)) / tonumber(ARGV[2]);
for _ = 1, tonumber(c) do
    redis.call('RPUSH', KEYS[1], ARGV[1])
end
redis.call('LTRIM', KEYS[1], tonumber(0), tonumber(ARGV[3]));
local count = redis.call('LLEN', KEYS[1]);
local min = math.min(tonumber(count), tonumber(ARGV[4]));
for _ = 1, tonumber(min) do
    redis.call('LPOP', KEYS[1]);
end
return min;

eval "" 1 tokenBucket 10000 500 100 5

